// <auto-generated />
using System;
using LunaMars.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace LunaMars.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LunaMars.API.Models.AlertaColonia", b =>
                {
                    b.Property<int>("idAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAlerta"));

                    b.Property<DateTime>("dtCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("dtFinalizacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("mensagem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("nivelRisco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("setorColoniaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("statusAlerta")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("idAlerta");

                    b.HasIndex("setorColoniaId");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("LunaMars.API.Models.ColoniaEspacial", b =>
                {
                    b.Property<int>("idColonia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idColonia"));

                    b.Property<int>("capacidadePessoas")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("dtCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("localizacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("nomeColonia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("idColonia");

                    b.ToTable("Colonias");
                });

            modelBuilder.Entity("LunaMars.API.Models.LeituraSensor", b =>
                {
                    b.Property<int>("idLeitura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLeitura"));

                    b.Property<DateTime>("dtLeitura")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("sensorAmbientalId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("setorColoniaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("tipoSensor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("unidadeMedida")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("valor")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("idLeitura");

                    b.HasIndex("sensorAmbientalId");

                    b.HasIndex("setorColoniaId");

                    b.ToTable("Leituras");
                });

            modelBuilder.Entity("LunaMars.API.Models.MissaoResposta", b =>
                {
                    b.Property<int>("idMissao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMissao"));

                    b.Property<int>("alertaColoniaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("dtFim")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("dtInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("statusMissao")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("idMissao");

                    b.HasIndex("alertaColoniaId");

                    b.ToTable("Missoes");
                });

            modelBuilder.Entity("LunaMars.API.Models.RecursoVital", b =>
                {
                    b.Property<int>("idRecurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRecurso"));

                    b.Property<int>("coloniaEspacialId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("dtValidade")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<double>("nivelMinimo")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("quantidade")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("tipoRecurso")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("unidadeMedida")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("idRecurso");

                    b.HasIndex("coloniaEspacialId");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("LunaMars.API.Models.RoverExploracao", b =>
                {
                    b.Property<int>("idEquipamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEquipamento"));

                    b.Property<int>("ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<double>("distanciaPercorridaKm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("dtAtivacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<double>("nivelBateria")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("nomeEquipamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("idEquipamento");

                    b.ToTable("Rovers");
                });

            modelBuilder.Entity("LunaMars.API.Models.SateliteOrbital", b =>
                {
                    b.Property<int>("idEquipamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEquipamento"));

                    b.Property<string>("agenciaOperadora")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime>("dtAtivacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("nomeEquipamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("orbita")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("idEquipamento");

                    b.ToTable("Satelites");
                });

            modelBuilder.Entity("LunaMars.API.Models.SensorAmbiental", b =>
                {
                    b.Property<int>("idSensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSensor"));

                    b.Property<int>("ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("nomeSensor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("setorColoniaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("tipoSensor")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("idSensor");

                    b.HasIndex("setorColoniaId");

                    b.ToTable("Sensores");
                });

            modelBuilder.Entity("LunaMars.API.Models.SetorColonia", b =>
                {
                    b.Property<int>("idSetor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSetor"));

                    b.Property<int>("ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("coloniaEspacialId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("nomeSetor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("pressaoInterna")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("temperaturaAtual")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("tipoSetor")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("idSetor");

                    b.HasIndex("coloniaEspacialId");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("LunaMars.API.Models.AlertaColonia", b =>
                {
                    b.HasOne("LunaMars.API.Models.SetorColonia", "SetorColonia")
                        .WithMany()
                        .HasForeignKey("setorColoniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SetorColonia");
                });

            modelBuilder.Entity("LunaMars.API.Models.LeituraSensor", b =>
                {
                    b.HasOne("LunaMars.API.Models.SensorAmbiental", "SensorAmbiental")
                        .WithMany("Leituras")
                        .HasForeignKey("sensorAmbientalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LunaMars.API.Models.SetorColonia", "SetorColonia")
                        .WithMany("Leituras")
                        .HasForeignKey("setorColoniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SensorAmbiental");

                    b.Navigation("SetorColonia");
                });

            modelBuilder.Entity("LunaMars.API.Models.MissaoResposta", b =>
                {
                    b.HasOne("LunaMars.API.Models.AlertaColonia", "AlertaColonia")
                        .WithMany("Missoes")
                        .HasForeignKey("alertaColoniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertaColonia");
                });

            modelBuilder.Entity("LunaMars.API.Models.RecursoVital", b =>
                {
                    b.HasOne("LunaMars.API.Models.ColoniaEspacial", "ColoniaEspacial")
                        .WithMany("Recursos")
                        .HasForeignKey("coloniaEspacialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColoniaEspacial");
                });

            modelBuilder.Entity("LunaMars.API.Models.SensorAmbiental", b =>
                {
                    b.HasOne("LunaMars.API.Models.SetorColonia", "SetorColonia")
                        .WithMany("Sensores")
                        .HasForeignKey("setorColoniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SetorColonia");
                });

            modelBuilder.Entity("LunaMars.API.Models.SetorColonia", b =>
                {
                    b.HasOne("LunaMars.API.Models.ColoniaEspacial", "ColoniaEspacial")
                        .WithMany("Setores")
                        .HasForeignKey("coloniaEspacialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColoniaEspacial");
                });

            modelBuilder.Entity("LunaMars.API.Models.AlertaColonia", b =>
                {
                    b.Navigation("Missoes");
                });

            modelBuilder.Entity("LunaMars.API.Models.ColoniaEspacial", b =>
                {
                    b.Navigation("Recursos");

                    b.Navigation("Setores");
                });

            modelBuilder.Entity("LunaMars.API.Models.SensorAmbiental", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("LunaMars.API.Models.SetorColonia", b =>
                {
                    b.Navigation("Leituras");

                    b.Navigation("Sensores");
                });
#pragma warning restore 612, 618
        }
    }
}
